### ISSUE TITLE
Re-sterilization and reuse of Personal Protective Equipment (PPE)

### ISSUE THREAD

**Issue by kristiholmes** [Chicago-COVID-19/Evidence-Search-Synthesis#1]
The most urgent search need currently is around re-sterilization and reuse of Personal protective equipment, commonly referred to as "PPE" - what techniques can be used and what is most effective to inactivate virus particles (irradiation, autoclaving, other sterilization approaches).  They need to know what they can do to safely reuse PPE.

Preferred output: A focused set of references

**Comment by lodwyer** [comment]
Completed and added to Google Drive Completed Queries folder: https://drive.google.com/drive/folders/1a1niFnJfhzTL6ZvjUvQFPhT6KquhN5R9
